---
abstract: 'Convert PDF to XML'
author:
  - 'Joerg Tiedemann'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-PDF2XML
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  File::ShareDir: 0
requires:
  FindBin: 0
  Getopt::Std: 0
  IPC::Open2: 0
  XML::Parser: 0
  XML::Writer: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.2.1
